### PR TITLE
add ds1302

### PR DESCRIPTION
**Pull request by Utyff**
I have added the use of DS1302. Would you like to use it?

### CODE REVIEW

**Comment by Utyff** [comment]
Here you can get schematics of 303wifilc01
https://oshwlab.com/utyf/303wifilc01

**Comment by maarten-pennings** [comment]
Hi Utyff,

I have not done many pull request, so this is all completely new to me. So go slow please.

(1) I like that you have a made a schematic. What shall I do, link somewhere from my github to your oshwlab?

(2) I like that you made a standalone ds1302test. could you put that in an isolated pull request so that I can pull that in.
Will you include an update in the readme.md, or do you want me to do that?

(3) I have to admit that I'm less happy with the integration of ds1302 in nCLC. I would like to keep that separated. nCLC uses NTP (time from internet, that is what the n in nCLC stands for); it does not use the DS1302. I would prefer to have a separate ino (lCLC local clock) that does not use internet (NTP), and only the DS1302. We could make a third ino (dCLC, dual clock) that uses NTP and DS1302. What is you view on this?

Thanks for the work,

Maarten

**Comment by maarten-pennings** [comment]
I did a quick review of the schematic, the labels around the 7segment are all "A"

image

**Comment by Utyff** [comment]
Hi Maarten
Go slow :)
You can use my code however you like. You can reject poll request and edit and commit any files. If you write "thanks to Utyf" - I'll be happy :)

(1) I think better add schematics to readme as picture and give link to oshwlab project. Peaple can use both way.

(2) Reject this poll request and add the files you like.
 I don't like writing readme :) could you please do that? DS1302 is simple. I did the test in one evening

(3) GitHub shows that I replace nCLC.ino, but I have add to nCLC just ~30 code lines. Compare files and you will see.
- The RTC time is used to start the clock if the RTC has a valid time
- RTC updated every times when NTP sync
That's all that has changed.. NTP still working and has priority over RTC
But you can do your version. I just give you idea and example.

> I did a quick review of the schematic, the labels around the 7segment are all "A"
It was TODO and I forget it. Fixed. :)

**Comment by Utyff** [comment]
If you replace the battery with a rechargeable battery or super capacitor DS1302 can charge it. Here is an example of how to activate the charge.
https://github.com/Utyff/303WIFILC01/commit/a5bfbb1ef8bbf91ab9ad095717f101a5ab2ac012
But you can not activate the charge if a lithium battery is used. It might explode.

**Comment by maarten-pennings** [comment]
Thanks Utyff, all your work is merged now. I you see an error, omission or have any other remark, please let me know.

**Comment by Utyff** [comment]
Maarten, thank you. I only bought this clock because I found your repository. I like this clock and I use it. If I find any bug, I will definitely fix it.

**Pull request merged**
